### ISSUE TITLE
OperationCanceledException being thrown on ISocket.ConnectAsync and ISocket.Dispose

### ISSUE THREAD

**Issue by alexbfreeman** [heroiclabs/nakama-dotnet#71] opened 2021-07-29 16:41 UTC
Hello everyone,

I'm trying to close a socket connection by calling the CloseAsync method of Socket.cs. This exception is being thrown and I think I know the reason

```
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at Nakama.Ninja.WebSockets.Internal.BinaryReaderWriter.ReadExactly(Int32 length, Stream stream, ArraySegment`1 buffer, CancellationToken cancellationToken) in /Users/alfreeman/Github/nakama-dotnet/src/Nakama/Ninja.WebSockets/Internal/BinaryReaderWriter.cs:line 49
   at Nakama.Ninja.WebSockets.Internal.WebSocketFrameReader.ReadAsync(Stream fromStream, ArraySegment`1 intoBuffer, CancellationToken cancellationToken) in /Users/alfreeman/Github/nakama-dotnet/src/Nakama/Ninja.WebSockets/Internal/WebSocketFrameReader.cs:line 50
   at Nakama.Ninja.WebSockets.Internal.WebSocketImplementation.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in /Users/alfreeman/Github/nakama-dotnet/src/Nakama/Ninja.WebSockets/Internal/WebSocketImplementation.cs:line 122
   at Nakama.Ninja.WebSockets.Internal.WebSocketImplementation.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in /Users/alfreeman/Github/nakama-dotnet/src/Nakama/Ninja.WebSockets/Internal/WebSocketImplementation.cs:line 142
   at Nakama.Ninja.WebSockets.Internal.WebSocketImplementation.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in /Users/alfreeman/Github/nakama-dotnet/src/Nakama/Ninja.WebSockets/Internal/WebSocketImplementation.cs:line 195
   at Nakama.WebSocketAdapter.ReceiveLoop(WebSocket webSocket, CancellationToken cancellationToken) in /Users/alfreeman/Github/nakama-dotnet/src/Nakama/WebSocketAdapter.cs:line 175
   at Nakama.WebSocketAdapter.Connect(Uri uri, Int32 timeout) in /Users/alfreeman/Github/nakama-dotnet/src/Nakama/WebSocketAdapter.cs:line 115
```

This is the Connect method from WebSocketAdapter.cs

```
public async void Connect(Uri uri, int timeout)
        {
            if (_webSocket != null)
            {
                ReceivedError?.Invoke(new SocketException((int) SocketError.IsConnected));
                return;
            }

            _cancellationSource = new CancellationTokenSource();
            _uri = uri;
            IsConnecting = true;

            var clientFactory = new WebSocketClientFactory();
            try
            {
                var cts = new CancellationTokenSource(TimeSpan.FromSeconds(timeout));
                var lcts = CancellationTokenSource.CreateLinkedTokenSource(_cancellationSource.Token, cts.Token);
                using (_webSocket = await clientFactory.ConnectAsync(_uri, _options, lcts.Token))
                {
                    IsConnected = true;
                    IsConnecting = false;
                    Connected?.Invoke();

                    await ReceiveLoop(_webSocket, _cancellationSource.Token);
                }
            }
            catch (TaskCanceledException)
            {
                // No error, the socket got closed via the cancellation signal.
            }
            catch (ObjectDisposedException)
            {
                // No error, the socket got closed.
            }            
            catch (Exception e)
            {
                ReceivedError?.Invoke(e);
            }
            finally
            {
                Close();
                Closed?.Invoke();
            }
        }
```

It is not catching the case where a OperationCanceledException is thrown because a cancellation request has been made.  Is this intentional? Wouldn't it be more appropriate to check if a cancellation has been requested and not throw an error if so? For example

```
           catch (OperationCanceledException ex)
            {
                if(!ex.CancellationToken.IsCancellationRequested)
                {
                    ReceivedError?.Invoke(ex);
                }
            }
```

**Comment by lugehorsam** [comment] 2021-07-30 13:01
Hey @alexbfreeman, I can understand why you may expect an error not to be thrown since you are the one initiating the cancellation. However, this is a bit of a double-edged sword because other users may actually expect it to throw. Also, there is not always a way to detect what the source of a cancellation is from the perspective of the `Task`.

In a gray area like this we defer to Microsoft which recommends that you throw a cancellation exception if a user cancels their own `Task`: https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-cancellation

Note that you _can_ check the status on the cancelled `Task` upon catching the exception. It will be a `Canceled` status. So, you at least have that information.

**Comment by lugehorsam** [comment] 2021-07-30 13:04
Actually @alexbfreeman I think there may be a few related issues with this block. I'll circle back with the team.

**Comment by lugehorsam** [comment] 2021-07-30 13:33
@alexbfreeman I wanted to confirm that you are closing the connection while the socket is connecting? If so, this is expected behavior. Otherwise it may not be.

**Comment by alexbfreeman** [comment] 2021-07-30 14:41
Yes, it's an OperationCanceledException. I can't properly catch the exception on my code because it happens in the inner loop (ReceiveLoop), which is inside an async void method (see https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming on why we should avoid async void methods except if it's an event handler).

I could wait for a OnSocketError event and check if it's an OperationCanceledException, but there might be other reasons 
for the exception other than me closing the connection.

And no, I'm not closing the connection while the socket is connecting.

**Comment by alexbfreeman** [comment] 2021-07-30 16:12
Could MemoryStream.ReadAsync be returning an OperationCanceledException instead of a canceled task?

**Comment by lugehorsam** [comment] 2021-07-30 17:51
It's possible. I'll have a look later today or Monday to see if there's something I can simplify and make more predictable as to what exceptions are thrown when.

**Comment by alexbfreeman** [comment] 2021-07-30 20:02
After a few tests I might have another idea on what's going on... Please correct me if I'm out of my mind.

I think MemoryStream.ReadAsync **is** returning a cancelled task. 

Now... when the Nakama client awaits on said task it will throw a TaskCanceledException. However, WebSocketImplementation.ReceiveAsync is catching and throwing a 
OperationCanceledException. So TaskCanceledException turns into OperationCanceledException. Now the catch in  WebSocketAdapter for TaskCanceledException won't work and the OperationCanceledException gets bubbled up. Can this be it?

**Comment by lugehorsam** [comment] 2021-08-02 14:03
@alexbfreeman Agreed on the `async void` point -- I'll make that change. The original author is on vacation for a week so I'll probably wait for his review in case he had a particular behind the `async void`. 

What's odd to me though is I can't reproduce the throwing of an exception while closing a socket in my .NET test, regardless of whether or not the socket lifecycle methods return `Task` or not. 

https://github.com/heroiclabs/nakama-dotnet/blob/master/tests/Nakama.Tests/Socket/WebSocketTest.cs#L72

For example: https://github.com/heroiclabs/nakama-dotnet/blob/master/tests/Nakama.Tests/Socket/WebSocketTest.cs#L72
has always passed for me, again regardless of `Task` or `void`. If an exception were thrown, the test would not pass.

Perhaps this exception is thrown when using Unity's synchronization context but not the standard .NET one.

**Comment by lugehorsam** [comment] 2021-08-02 14:40
I'm also having trouble triggering the exception to be thrown in Unity. The socket connects and closes without any errors or exceptions. If you have an example reproduction though, that would be great.

**Comment by Donnotron666** [comment] 2021-11-17 17:35
Hi! Just weighing in! This exception has been plaguing our project for a bit, even though I've never been able to reproduce it in Unity- it's our number one exception that appears in our automated exception tracker.

**Comment by lugehorsam** [comment] 2021-11-17 17:58
@Donnotron666 A fix for this issue is under team review and will be included in the next Nakama release.

**Comment by GaNacereddine** [comment] 2022-09-06 22:47
@lugehorsam Can you share if this was ever fixed?

**Comment by lugehorsam** [comment] 2022-09-06 23:16
@GaNacereddine yes it should be fixed. I'll close out this issue.

**Closed by lugehorsam** 2022-09-06 23:16 UTC
